modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "furnies"
version = "${version}"
displayName = "Furnies"
authors = "LunazStudios"
description = '''
Furnies adds stylish and functional furniture to Minecraft, enhancing interior and exterior design.
'''
logoFile = "icon.png"

[[dependencies.furnies]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.furnies]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "furnies.mixins.json"
